19-rails-assocatiations/classy/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :regions
  # get "/regions/new", to: "regions#new", as: "new_region"
  # get "/regions/:id/edit", to: "regions#edit", as: "edit_region"

  resources :wines
  resources :cheeses
  #
  # get "/regions", to: 'regions#index', as: 'regions'
  # get "/regions/new", to: 'regions#new', as: 'new_region'
  # get "/regions/:id", to: 'regions#show', as: 'region'
  #
  # post "/regions", to: 'regions#create'
  #
  # get "/regions/:id/edit", to: 'regions#edit', as: 'edit_region'
  #
  # patch "/regions/:id", to: 'regions#update'
  # put "/regions/:id", to: 'regions#update'
  #
  # delete "/regions/:id", to: 'regions#destroy'
end

19-rails-assocatiations/classy/app/models/cheese.rb
class Cheese < ApplicationRecord
  has_many :pairings
  has_many :wines, through: :pairings
end

19-rails-assocatiations/classy/app/models/pairing.rb
class Pairing < ApplicationRecord
  belongs_to :cheese
  belongs_to :wine
end

19-rails-assocatiations/classy/app/models/region.rb
class Region < ApplicationRecord
  has_many :wines
  
  validates :name, uniqueness: true, presence: true
end

19-rails-assocatiations/classy/app/models/wine.rb
class Wine < ApplicationRecord
  belongs_to :region
  has_many :pairings
  has_many :cheeses, through: :pairings
end

19-rails-assocatiations/classy/app/controllers/cheeses_controller.rb
class CheesesController < ApplicationController
  before_action :set_cheese, only: [:show, :edit, :update, :destroy]
  before_action :set_wines, only: [:new, :edit]

  def index
    @cheeses = Cheese.all
  end

  def show
  end

  def new
    @cheese = Cheese.new
  end

  def create
    @cheese = Cheese.create(cheese_params)
    if @cheese.valid?
      redirect_to @cheese
    else
      flash[:errors] = @cheese.errors.full_messages
      redirect_to new_cheese_path
    end
  end

  def edit
  end

  def update
    @cheese.update(cheese_params)
    if @cheese.valid?
      redirect_to @cheese
    else
      flash[:errors] = @cheese.errors.full_messages
      redirect_to edit_cheese_path(@cheese)
    end
  end

  def destroy
    @cheese.destroy
    redirect_to cheeses_path
  end

  private
  def cheese_params
    params.require(:cheese).permit(:name, wine_ids: [])
  end

  def set_cheese
    @cheese = Cheese.find(params[:id])
  end

  def set_wines
    @wines = Wine.all.sort_by { |w| w.name }
  end
end

19-rails-assocatiations/classy/app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  def index
    @regions = Region.all
  end

  def show
  end

  def new
    @region = Region.new
  end

  def create
    @region = Region.create(region_params)
    if @region.valid?
      redirect_to @region
    else
      flash[:errors] = @region.errors.full_messages
      redirect_to new_region_path
    end
  end

  def edit
  end

  def update
    @region.update(region_params)
    if @region.valid?
      redirect_to @region
    else
      flash[:errors] = @region.errors.full_messages
      redirect_to edit_region_path(@region)
    end
  end

  def destroy
    @region.destroy
    redirect_to regions_path
  end

  private
  def region_params
    params.require(:region).permit(:name)
  end

  def set_region
    @region = Region.find(params[:id])
  end
end

19-rails-assocatiations/classy/app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [:show, :edit, :update, :destroy]
  before_action :set_regions, only: [:new, :edit]
  before_action :set_cheeses, only: [:new, :edit]

  def index
    @wines = Wine.all
  end

  def show
  end

  def new
    @wine = Wine.new
  end

  def create
    @wine = Wine.create(wine_params)
    if @wine.valid?
      redirect_to @wine
    else
      flash[:errors] = @wine.errors.full_messages
      redirect_to new_wine_path
    end
  end

  def edit
  end

  def update
    @wine.update(wine_params)
    if @wine.valid?
      redirect_to @wine
    else
      flash[:errors] = @wine.errors.full_messages
      redirect_to edit_wine_path(@wine)
    end
  end

  def destroy
    @wine.destroy
    redirect_to wines_path
  end

  private

  def wine_params
    params.require(:wine).permit(:name, :region_id, cheese_ids: [])
  end

  def set_wine
    @wine = Wine.find(params[:id])
  end

  def set_regions
    @regions = Region.all.sort_by { |r| r.name }
  end

  def set_cheeses
    @cheeses = Cheese.all.sort_by { |c| c.name }
  end
end

19-rails-assocatiations/classy/app/views/cheeses/_form.html.erb
<%= render "errors/errors" %>

<%= form_for @cheese do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.collection_check_boxes :wine_ids, @wines, :id, :name %>
  <%= f.submit %>
<% end %>

19-rails-assocatiations/classy/app/views/cheeses/edit.html.erb
<h1>Edit Cheese</h1>

<%= link_to "go back", @cheese %>

<%= render "form" %>

<%= form_tag cheese_path(@cheese), method: "delete" do  %>
  <%= submit_tag "Delete Cheese" %>
<% end %>

19-rails-assocatiations/classy/app/views/cheeses/index.html.erb
<h1>All Cheeses</h1>

<%= link_to "Make new Cheese", new_cheese_path %>

<ul>
  <% @cheeses.each do |cheese| %>
    <li><%= link_to cheese.name, cheese %></li>
  <% end %>
</ul>

19-rails-assocatiations/classy/app/views/cheeses/new.html.erb
<h1>Make new Cheese</h1>

<%= link_to "go back", cheeses_path %>

<%= render "form" %>

19-rails-assocatiations/classy/app/views/cheeses/show.html.erb
<h1><%= @cheese.name %></h1>

<% if @cheese.wines.length > 0 %>
  <p>This cheese might pair well with the following</p>
  <ul>
    <% @cheese.wines.each do |wine| %>
      <li><%= link_to wine.name, wine %> from the <%= link_to wine.region.name, wine.region %> region.</li>
    <% end %>
  </ul>
<% end %>


<%= link_to "All Cheeses", cheeses_path %>
<%= link_to "Edit Cheese", edit_cheese_path(@cheese) %>

19-rails-assocatiations/classy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Classy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

19-rails-assocatiations/classy/app/views/regions/_form.html.erb
<%= render "errors/errors" %>

<%= form_for @region do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

19-rails-assocatiations/classy/app/views/regions/edit.html.erb
<h1>Edit Region</h1>

<%= link_to "go back", @region %>

<%= render "form" %>

<%= form_tag region_path(@region), method: "delete" do  %>
  <%= submit_tag "Delete Region" %>
<% end %>

19-rails-assocatiations/classy/app/views/regions/index.html.erb
<h1>All Regions</h1>

<%= link_to "Make new Region", new_region_path %>

<ul>
  <% @regions.each do |region| %>
    <li><%= link_to region.name, region %></li>
  <% end %>
</ul>

19-rails-assocatiations/classy/app/views/regions/new.html.erb
<h1>Make new Region</h1>

<%= link_to "go back", regions_path %>

<%= render "form" %>

19-rails-assocatiations/classy/app/views/regions/show.html.erb
<h1><%= @region.name %></h1>

<% if @region.wines.length > 0 %>
  <p>The following wines are from this beautiful region.</p>
  <ul>
    <% @region.wines.each do |wine| %>
      <li><%= link_to wine.name, wine %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to "All Regions", regions_path %>
<%= link_to "Edit Region", edit_region_path(@region) %>

19-rails-assocatiations/classy/app/views/wines/_form.html.erb
<%= render "errors/errors" %>

<%= form_for @wine do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.collection_select :region_id, @regions, :id, :name %>
  <%= f.collection_check_boxes :cheese_ids, @cheeses, :id, :name %>
  <%= f.submit %>
<% end %>

19-rails-assocatiations/classy/app/views/wines/edit.html.erb
<h1>Edit Wine</h1>

<%= link_to "go back", @wine %>

<%= render "form" %>

<%= form_tag wine_path(@wine), method: "delete" do  %>
  <%= submit_tag "Delete Wine" %>
<% end %>

19-rails-assocatiations/classy/app/views/wines/index.html.erb
<h1>All Wines</h1>

<%= link_to "Make new Wine", new_wine_path %>

<ul>
  <% @wines.each do |wine| %>
    <li><%= link_to wine.name, wine %></li>
  <% end %>
</ul>

19-rails-assocatiations/classy/app/views/wines/new.html.erb
<h1>Make new Wine</h1>

<%= link_to "go back", wines_path %>

<%= render "form" %>

19-rails-assocatiations/classy/app/views/wines/show.html.erb
<h1><%= @wine.name %></h1>

<% if @wine.cheeses.length > 0 %>
  <p>This wine might pair well with the following cheeses:</p>
  <ul>
    <% @wine.cheeses.each do |cheese| %>
      <li><%= link_to cheese.name, cheese %></li>
    <% end %>
  </ul>
<% end %>

<p>This wine belongs to the <%= link_to @wine.region.name, @wine.region %> region.</p>

<%= link_to "All Wines", wines_path %>
<%= link_to "Edit Wine", edit_wine_path(@wine) %>