21-rails-auth/authapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :books, only: [:index, :show]
  resources :users, only: [:index, :show, :create, :edit, :update]

  get "/login", to: 'sessions#new', as: 'login'
  post "/sessions", to: 'sessions#create', as: 'sessions'
  get "/signup", to: 'users#new', as: 'signup'
  post "/logout", to: 'sessions#destroy', as: 'logout'
end

21-rails-auth/authapp/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

21-rails-auth/authapp/app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  has_many :books
  has_secure_password
end

21-rails-auth/authapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    else
      User.new
    end
  end

  def logged_in?
    !!current_user.id
  end

  def authorized?
    if !logged_in?
      flash[:authorized] = "You aren't logged in!"
      redirect_to login_path
      false
    else
      true
    end
  end

  def authorized_for(user_id)
    if authorized? && current_user.id != user_id.to_i
      flash[:authorized] = "You can't see that u thief!"
      redirect_to current_user
    end
  end
end

21-rails-auth/authapp/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    session[:seen_book_ids] ||= []

    @books = Book.all.select do |book|
      !session[:seen_book_ids].include?(book.id)
    end
  end

  def show
    @book = Book.find(params[:id])
    session[:seen_book_ids] ||= []
    session[:seen_book_ids] << @book.id
  end
end

21-rails-auth/authapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user
    else
      flash[:errors] = ["Cannot Find User or validate password"]
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    # session.delete(:user_id)
    redirect_to login_path
  end
end

21-rails-auth/authapp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create!(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to @user
    end
  end

  def edit
    authorized_for(params[:id])
    @user = User.find(params[:id])
    @books = Book.where(user_id: nil).or(Book.where(user_id: @user.id))
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end


  private
  def user_params
    params.require(:user).permit(:username, :password, book_ids: [])
  end
end

21-rails-auth/authapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:authorized] %>
      <p style="color: red;"><%= flash[:authorized] %></p>
    <% end %>
    <% if logged_in? %>
      <%= link_to "Log Out", logout_path, method: 'post' %>
    <% else %>
      <%= link_to "Log In", login_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

21-rails-auth/authapp/app/views/users/edit.html.erb
<h1>Your account settings</h1>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.collection_check_boxes :book_ids, @books, :id, :title do |cb| %>
    <div>
      <%= cb.check_box %>
      <%= cb.label %>
    </div>
  <% end %>
  <%= f.submit %>
<% end %>

21-rails-auth/authapp/app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username, user %></li>
  <% end %>
</ul>

21-rails-auth/authapp/app/views/users/new.html.erb
<h1>Sign up here!!</h1>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit %>
<% end %>

21-rails-auth/authapp/app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<% if @user == current_user %>
  <h2>Welcome back</h2>
  <%= link_to "Would you like to modify your library?", edit_user_path(@user) %>
<% end %>


<% if @user.books.length > 0 %>
  <h3>Ur Library</h3>
  <ul>
    <% @user.books.each do |book| %>
      <li><%= link_to book.title, book %></li>
    <% end %>
  </ul>
<% end %>